### ISSUE TITLE
Cannot Remap keys on Phillips G404 Keyboard

### ISSUE THREAD

**Issue by aramacs** [wez/evremap#37]
Like the guy in the issues with the cherry keyboard mine shows 4 diferent names. The first one shows an error "No device found with name `SINO WEALTH Gaming KB`". The other 3 executes the loop but nothing changes. 

![Screenshot_2023-07-29-22-14-14_12543](https://github.com/wez/evremap/assets/69637662/14f85834-a00e-4e15-a0cb-85ce90a8669e)

**Comment by wez** [comment]
If you're still interested in resolving this, `main` now has a `debug-events` subcommand that can help you to understand which keys are emitting which events.

I'm going to close this because I'm assuming that you've long-since moved on.

**Comment by akarinotomoshibi** [comment]
This issue is caused by the presence of trailing whitespace at the end of the device name value in device_name.
Since this occurs spontaneously within the system, the underlying root cause remains unclear.
Based on my observations, it would be reasonable to conclude that this is likely an issue stemming from the Linux kernel, the USB device, or the driver itself.
